# Use the official Python image from Docker Hub
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Install any necessary system dependencies (SQLite doesn't need MySQL/MariaDB dependencies)
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy Python requirements
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django project files into the container
COPY . /app/

# Expose the port that Django will run on
EXPOSE 8003

# Run migrations and the Django server
CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && gunicorn --workers 4 --bind 0.0.0.0:8003 accountsnew.wsgi:application"]
